updated bashly

diff --git a/hydrogen/h b/hydrogen/h
--- a/hydrogen/h
+++ b/hydrogen/h
@@ -1,4 +1,4 @@
-#!/nix/store/wadmyilr414n7bimxysbny876i2vlm5r-bash-5.1-p8/bin/bash
+#!/nix/store/30j23057fqnnc1p4jqmq73p0gxgn0frq-bash-5.1-p16/bin/bash
 # This script was generated by bashly (https://github.com/DannyBen/bashly)
 # Modifying it manually is not recommended
 
@@ -36,6 +36,7 @@ h_usage() {
   echo "  update    Update flake inputs"
   echo "  test      Rebuild and test the system"
   echo "  search    Search for a package in nixpkgs"
+  echo "  shell     Setup files for an adhoc shell in the directory"
   echo
 
   if [[ -n $long_usage ]]; then
@@ -217,6 +218,51 @@ h_search_usage() {
   fi
 }
 
+# :command.usage
+h_shell_usage() {
+  if [[ -n $long_usage ]]; then
+    printf "h shell - Setup files for an adhoc shell in the directory\n"
+    echo
+
+  else
+    printf "h shell - Setup files for an adhoc shell in the directory\n"
+    echo
+
+  fi
+
+  printf "Shortcut: s\n"
+  echo
+
+  printf "Usage:\n"
+  printf "  h shell PACKAGES\n"
+  printf "  h shell --help | -h\n"
+  echo
+
+  if [[ -n $long_usage ]]; then
+    printf "Options:\n"
+    # :command.usage_fixed_flags
+    echo "  --help, -h"
+    printf "    Show this help\n"
+    echo
+
+    # :command.usage_args
+    printf "Arguments:\n"
+
+    # :argument.usage
+    echo "  PACKAGES"
+    printf "    Packages to add to the shell\n"
+    echo
+
+    # :command.usage_examples
+    printf "Examples:\n"
+
+    printf "  h s hello\n"
+    printf "  h shell hello\n"
+    echo
+
+  fi
+}
+
 # :command.normalize_input
 normalize_input() {
   local arg flags
@@ -375,6 +421,24 @@ h_search_command() {
   nix search nixpkgs $pkg
 }
 
+# :command.function
+h_shell_command() {
+  # :src/shell_command.sh
+  inspect_args
+  pkgs=''
+  eval "pkgs=(${args[packages]})"
+  echo ${pkgs}
+
+  echo " { pkgs ? import <nixpkgs> {}}:
+  pkgs.mkShell {
+    nativeBuildInputs = with pkgs; [ ${pkgs} ];
+  }" >> shell.nix
+
+  echo "use nix" >> .envrc
+
+  direnv allow
+}
+
 # :command.parse_requirements
 parse_requirements() {
   # :command.fixed_flag_filter
@@ -425,6 +489,13 @@ parse_requirements() {
     action="search"
     shift
     h_search_parse_requirements "$@"
+    shift $#
+    ;;
+
+  shell | s )
+    action="shell"
+    shift
+    h_shell_parse_requirements "$@"
     shift $#
     ;;
 
@@ -662,6 +733,63 @@ h_search_parse_requirements() {
   # :command.whitelist_filter
 }
 
+# :command.parse_requirements
+h_shell_parse_requirements() {
+  # :command.fixed_flag_filter
+  case "$1" in
+  --version | -v )
+    version_command
+    exit
+    ;;
+
+  --help | -h )
+    long_usage=yes
+    h_shell_usage
+    exit
+    ;;
+
+  esac
+  # :command.environment_variables_filter
+  # :command.dependencies_filter
+  # :command.command_filter
+  action="shell"
+  # :command.required_args_filter
+  if [[ $1 && $1 != -* ]]; then
+    args[packages]=$1
+    shift
+  else
+    printf "missing required argument: PACKAGES\nusage: h shell PACKAGES\n"
+    exit 1
+  fi
+  # :command.required_flags_filter
+  # :command.parse_requirements_while
+  while [[ $# -gt 0 ]]; do
+    key="$1"
+    case "$key" in
+
+    -* )
+      printf "invalid option: %s\n" "$key"
+      exit 1
+      ;;
+
+    * )
+      # :command.parse_requirements_case
+      if [[ ! ${args[packages]} ]]; then
+        args[packages]=$1
+        shift
+      else
+        printf "invalid argument: %s\n" "$key"
+        exit 1
+      fi
+      ;;
+
+    esac
+  done
+  # :command.catch_all_filter
+  # :command.default_assignments
+  # :command.whitelist_filter
+}
+
 # :command.initialize
 initialize() {
   version="0.1.0"
@@ -715,6 +843,14 @@ run() {
       h_search_usage
     else
       h_search_command
+    fi
+
+  elif [[ $action == "shell" ]]; then
+    if [[ ${args[--help]} ]]; then
+      long_usage=yes
+      h_shell_usage
+    else
+      h_shell_command
     fi
 
   elif [[ $action == "root" ]]; then
