updated hydrogen

diff --git a/hydrogen/h b/hydrogen/h
--- a/hydrogen/h
+++ b/hydrogen/h
@@ -1,12 +1,14 @@
 #!/nix/store/30j23057fqnnc1p4jqmq73p0gxgn0frq-bash-5.1-p16/bin/bash
-# This script was generated by bashly (https://github.com/DannyBen/bashly)
+# This script was generated by bashly 0.7.9 (https://bashly.dannyb.co)
 # Modifying it manually is not recommended
 
-# :script.bash3_bouncer
+# :wrapper.bash3_bouncer
 if [[ "${BASH_VERSINFO:-0}" -lt 4 ]]; then
   printf "bash version 4 or higher is required\n"
   exit 1
 fi
+
+# :command.master_script
 
 # :command.version_command
 version_command() {
@@ -133,6 +135,14 @@ h_update_usage() {
     printf "    Inputs to update\n"
     echo
 
+    # :command.usage_examples
+    printf "Examples:\n"
+
+    printf "  h update\n"
+    printf "  h u\n"
+    printf "  h u nixpkgs\n"
+    echo
+
   fi
 }
 
@@ -234,7 +244,7 @@ h_shell_usage() {
   echo
 
   printf "Usage:\n"
-  printf "  h shell PACKAGES\n"
+  printf "  h shell PACKAGES...\n"
   printf "  h shell --help | -h\n"
   echo
 
@@ -249,7 +259,7 @@ h_shell_usage() {
     printf "Arguments:\n"
 
     # :argument.usage
-    echo "  PACKAGES"
+    echo "  PACKAGES..."
     printf "    Packages to add to the shell\n"
     echo
 
@@ -308,7 +318,7 @@ inspect_args() {
 }
 
 # :command.user_lib
-# :src/lib/colors.sh
+# src/lib/colors.sh
 # ---
 # Color functions
 # This file is a part of Bashly standard library
@@ -343,7 +353,7 @@ blue_underlined() { printf "\e[4;34m%b\e[0m\n" "$*"; }
 magenta_underlined() { printf "\e[4;35m%b\e[0m\n" "$*"; }
 cyan_underlined() { printf "\e[4;36m%b\e[0m\n" "$*"; }
 
-# :src/lib/logger.sh
+# src/lib/logger.sh
 info() { printf "$(yellow_bold [HYDROGEN]) $(yellow $1)"; }
 error() { printf "$(red_bold [HYDROGEN]) $(red_underlined FAILED) $(red $1)\n"; }
 success() { printf "$(green_bold [HYDROGEN]) $(green $1)\n"; }
@@ -351,7 +361,7 @@ success() { printf "$(green_bold [HYDROGEN]) $(green $1)\n"; }
 # :command.command_functions
 # :command.function
 h_rebuild_command() {
-  # :src/rebuild_command.sh
+  # src/rebuild_command.sh
   mod=${args[module]}
 
   if [ "$mod" == "hm" ] || [ "$mod" == "home-manager" ]; then
@@ -379,7 +389,7 @@ h_rebuild_command() {
 
 # :command.function
 h_update_command() {
-  # :src/update_command.sh
+  # src/update_command.sh
   input=${args[input]}
 
   pushd ~/.dotfiles
@@ -397,7 +407,7 @@ h_update_command() {
 
 # :command.function
 h_test_command() {
-  # :src/test_command.sh
+  # src/test_command.sh
   info "Rebuilding NixOS configurations in TESTING MODE...\n"
   RESULT=$(~/.dotfiles/scripts/test-system.sh 2>&1)
   if echo "${RESULT}" | grep "error"; then
@@ -411,7 +421,7 @@ h_test_command() {
 
 # :command.function
 h_search_command() {
-  # :src/search_command.sh
+  # src/search_command.sh
   #echo "# this file is located in 'src/search_command.sh'"
   #echo "# code for 'h search' goes here"
   #echo "# you can edit it freely and regenerate (it will not be overwritten)"
@@ -423,26 +433,34 @@ h_search_command() {
 
 # :command.function
 h_shell_command() {
-  # :src/shell_command.sh
-  inspect_args
+  # src/shell_command.sh
   pkgs=''
   eval "pkgs=(${args[packages]})"
-  echo ${pkgs}
+  final=''
+
+  [ -f shell.nix ] && error "shell.nix already exists." && exit 1
+
+  for i in "${pkgs[@]}"; do
+    final+=" "
+    final+=$i
+  done
 
   echo " { pkgs ? import <nixpkgs> {}}:
   pkgs.mkShell {
-    nativeBuildInputs = with pkgs; [ ${pkgs} ];
+    nativeBuildInputs = with pkgs; [ $final ];
   }" >> shell.nix
 
   echo "use nix" >> .envrc
 
   direnv allow
+
+  success "Done! Added the following packages:\n$final"
 }
 
 # :command.parse_requirements
 parse_requirements() {
-  # :command.fixed_flag_filter
-  case "$1" in
+  # :command.fixed_flags_filter
+  case "${1:-}" in
   --version | -v )
     version_command
     exit
@@ -458,7 +476,7 @@ parse_requirements() {
   # :command.environment_variables_filter
   # :command.dependencies_filter
   # :command.command_filter
-  action=$1
+  action=${1:-}
 
   case $action in
   -* )
@@ -506,14 +524,12 @@ parse_requirements() {
     ;;
 
   esac
-  # :command.required_args_filter
-  # :command.required_flags_filter
   # :command.parse_requirements_while
   while [[ $# -gt 0 ]]; do
     key="$1"
     case "$key" in
 
-    -* )
+    -?* )
       printf "invalid option: %s\n" "$key"
       exit 1
       ;;
@@ -526,20 +542,18 @@ parse_requirements() {
 
     esac
   done
+  # :command.required_args_filter
+  # :command.required_flags_filter
   # :command.catch_all_filter
   # :command.default_assignments
   # :command.whitelist_filter
+  # :command.user_filter
 }
 
 # :command.parse_requirements
 h_rebuild_parse_requirements() {
-  # :command.fixed_flag_filter
-  case "$1" in
-  --version | -v )
-    version_command
-    exit
-    ;;
-
+  # :command.fixed_flags_filter
+  case "${1:-}" in
   --help | -h )
     long_usage=yes
     h_rebuild_usage
@@ -551,21 +565,20 @@ h_rebuild_parse_requirements() {
   # :command.dependencies_filter
   # :command.command_filter
   action="rebuild"
-  # :command.required_args_filter
-  # :command.required_flags_filter
   # :command.parse_requirements_while
   while [[ $# -gt 0 ]]; do
     key="$1"
     case "$key" in
 
-    -* )
+    -?* )
       printf "invalid option: %s\n" "$key"
       exit 1
       ;;
 
     * )
       # :command.parse_requirements_case
-      if [[ ! ${args[module]} ]]; then
+      if [[ -z ${args[module]+x} ]]; then
+        # :argument.validations
         args[module]=$1
         shift
       else
@@ -576,20 +589,18 @@ h_rebuild_parse_requirements() {
 
     esac
   done
+  # :command.required_args_filter
+  # :command.required_flags_filter
   # :command.catch_all_filter
   # :command.default_assignments
   # :command.whitelist_filter
+  # :command.user_filter
 }
 
 # :command.parse_requirements
 h_update_parse_requirements() {
-  # :command.fixed_flag_filter
-  case "$1" in
-  --version | -v )
-    version_command
-    exit
-    ;;
-
+  # :command.fixed_flags_filter
+  case "${1:-}" in
   --help | -h )
     long_usage=yes
     h_update_usage
@@ -601,21 +612,20 @@ h_update_parse_requirements() {
   # :command.dependencies_filter
   # :command.command_filter
   action="update"
-  # :command.required_args_filter
-  # :command.required_flags_filter
   # :command.parse_requirements_while
   while [[ $# -gt 0 ]]; do
     key="$1"
     case "$key" in
 
-    -* )
+    -?* )
       printf "invalid option: %s\n" "$key"
       exit 1
       ;;
 
     * )
       # :command.parse_requirements_case
-      if [[ ! ${args[input]} ]]; then
+      if [[ -z ${args[input]+x} ]]; then
+        # :argument.validations
         args[input]=$1
         shift
       else
@@ -626,20 +636,18 @@ h_update_parse_requirements() {
 
     esac
   done
+  # :command.required_args_filter
+  # :command.required_flags_filter
   # :command.catch_all_filter
   # :command.default_assignments
   # :command.whitelist_filter
+  # :command.user_filter
 }
 
 # :command.parse_requirements
 h_test_parse_requirements() {
-  # :command.fixed_flag_filter
-  case "$1" in
-  --version | -v )
-    version_command
-    exit
-    ;;
-
+  # :command.fixed_flags_filter
+  case "${1:-}" in
   --help | -h )
     long_usage=yes
     h_test_usage
@@ -651,14 +659,12 @@ h_test_parse_requirements() {
   # :command.dependencies_filter
   # :command.command_filter
   action="test"
-  # :command.required_args_filter
-  # :command.required_flags_filter
   # :command.parse_requirements_while
   while [[ $# -gt 0 ]]; do
     key="$1"
     case "$key" in
 
-    -* )
+    -?* )
       printf "invalid option: %s\n" "$key"
       exit 1
       ;;
@@ -671,20 +677,18 @@ h_test_parse_requirements() {
 
     esac
   done
+  # :command.required_args_filter
+  # :command.required_flags_filter
   # :command.catch_all_filter
   # :command.default_assignments
   # :command.whitelist_filter
+  # :command.user_filter
 }
 
 # :command.parse_requirements
 h_search_parse_requirements() {
-  # :command.fixed_flag_filter
-  case "$1" in
-  --version | -v )
-    version_command
-    exit
-    ;;
-
+  # :command.fixed_flags_filter
+  case "${1:-}" in
   --help | -h )
     long_usage=yes
     h_search_usage
@@ -696,28 +700,20 @@ h_search_parse_requirements() {
   # :command.dependencies_filter
   # :command.command_filter
   action="search"
-  # :command.required_args_filter
-  if [[ $1 && $1 != -* ]]; then
-    args[package]=$1
-    shift
-  else
-    printf "missing required argument: PACKAGE\nusage: h search PACKAGE\n"
-    exit 1
-  fi
-  # :command.required_flags_filter
   # :command.parse_requirements_while
   while [[ $# -gt 0 ]]; do
     key="$1"
     case "$key" in
 
-    -* )
+    -?* )
       printf "invalid option: %s\n" "$key"
       exit 1
       ;;
 
     * )
       # :command.parse_requirements_case
-      if [[ ! ${args[package]} ]]; then
+      if [[ -z ${args[package]+x} ]]; then
+        # :argument.validations
         args[package]=$1
         shift
       else
@@ -728,20 +724,22 @@ h_search_parse_requirements() {
 
     esac
   done
+  # :command.required_args_filter
+  if [[ -z ${args[package]+x} ]]; then
+    printf "missing required argument: PACKAGE\nusage: h search PACKAGE\n"
+    exit 1
+  fi
+  # :command.required_flags_filter
   # :command.catch_all_filter
   # :command.default_assignments
   # :command.whitelist_filter
+  # :command.user_filter
 }
 
 # :command.parse_requirements
 h_shell_parse_requirements() {
-  # :command.fixed_flag_filter
-  case "$1" in
-  --version | -v )
-    version_command
-    exit
-    ;;
-
+  # :command.fixed_flags_filter
+  case "${1:-}" in
   --help | -h )
     long_usage=yes
     h_shell_usage
@@ -753,41 +751,40 @@ h_shell_parse_requirements() {
   # :command.dependencies_filter
   # :command.command_filter
   action="shell"
-  # :command.required_args_filter
-  if [[ $1 && $1 != -* ]]; then
-    args[packages]=$1
-    shift
-  else
-    printf "missing required argument: PACKAGES\nusage: h shell PACKAGES\n"
-    exit 1
-  fi
-  # :command.required_flags_filter
   # :command.parse_requirements_while
   while [[ $# -gt 0 ]]; do
     key="$1"
     case "$key" in
 
-    -* )
+    -?* )
       printf "invalid option: %s\n" "$key"
       exit 1
       ;;
 
     * )
       # :command.parse_requirements_case
-      if [[ ! ${args[packages]} ]]; then
-        args[packages]=$1
+      if [[ -z ${args[packages]+x} ]]; then
+        # :argument.validations
+        args[packages]="\"$1\""
         shift
       else
-        printf "invalid argument: %s\n" "$key"
-        exit 1
+        args[packages]="${args[packages]} \"$1\""
+        shift
       fi
       ;;
 
     esac
   done
+  # :command.required_args_filter
+  if [[ -z ${args[packages]+x} ]]; then
+    printf "missing required argument: PACKAGES\nusage: h shell PACKAGES...\n"
+    exit 1
+  fi
+  # :command.required_flags_filter
   # :command.catch_all_filter
   # :command.default_assignments
   # :command.whitelist_filter
+  # :command.user_filter
 }
 
 # :command.initialize
@@ -796,7 +793,7 @@ initialize() {
   long_usage=''
   set -e
 
-  # :src/initialize.sh
+  # src/initialize.sh
   # Code here runs inside the initialize() function
   # Use it for anything that you need to run before any other function, like
   # setting environment vairables:
@@ -807,14 +804,14 @@ initialize() {
 
 # :command.run
 run() {
-  declare -A args
-  declare -a other_args
-  declare -a input
+  declare -A args=()
+  declare -a other_args=()
+  declare -a input=()
   normalize_input "$@"
   parse_requirements "${input[@]}"
 
   if [[ $action == "rebuild" ]]; then
-    if [[ ${args[--help]} ]]; then
+    if [[ ${args[--help]:-} ]]; then
       long_usage=yes
       h_rebuild_usage
     else
@@ -822,7 +819,7 @@ run() {
     fi
 
   elif [[ $action == "update" ]]; then
-    if [[ ${args[--help]} ]]; then
+    if [[ ${args[--help]:-} ]]; then
       long_usage=yes
       h_update_usage
     else
@@ -830,7 +827,7 @@ run() {
     fi
 
   elif [[ $action == "test" ]]; then
-    if [[ ${args[--help]} ]]; then
+    if [[ ${args[--help]:-} ]]; then
       long_usage=yes
       h_test_usage
     else
@@ -838,7 +835,7 @@ run() {
     fi
 
   elif [[ $action == "search" ]]; then
-    if [[ ${args[--help]} ]]; then
+    if [[ ${args[--help]:-} ]]; then
       long_usage=yes
       h_search_usage
     else
@@ -846,7 +843,7 @@ run() {
     fi
 
   elif [[ $action == "shell" ]]; then
-    if [[ ${args[--help]} ]]; then
+    if [[ ${args[--help]:-} ]]; then
       long_usage=yes
       h_shell_usage
     else
